In [1]:
import pandas as pd

In [23]:
usageSampleDf = pd.read_csv('../raw-data/turnstile-usage/turnstile_170610.txt', header=0)

In [24]:
usageSampleDf.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/03/2017,00:00:00,REGULAR,6203652,2101226
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/03/2017,04:00:00,REGULAR,6203674,2101230
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/03/2017,08:00:00,REGULAR,6203688,2101260
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/03/2017,12:00:00,REGULAR,6203769,2101343
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/03/2017,16:00:00,REGULAR,6203987,2101401

In [32]:
usageSampleDf.columns = usageSampleDf.columns.str.strip()

In [34]:
usageSampleDf.sort_values('EXITS', ascending=False)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
69828,N208,R443,01-05-01,170 ST,BD,IND,06/09/2017,17:00:00,REGULAR,916848676,2087386866
69798,N208,R443,01-05-01,170 ST,BD,IND,06/04/2017,17:00:00,REGULAR,916848676,2087386866
69806,N208,R443,01-05-01,170 ST,BD,IND,06/06/2017,01:00:00,REGULAR,916848676,2087386866
69805,N208,R443,01-05-01,170 ST,BD,IND,06/05/2017,21:00:00,REGULAR,916848676,2087386866
69804,N208,R443,01-05-01,170 ST,BD,IND,06/05/2017,17:00:00,REGULAR,916848676,2087386866
69803,N208,R443,01-05-01,170 ST,BD,IND,06/05/2017,13:00:00,REGULAR,916848676,2087386866
69802,N208,R443,01-05-01,170 ST,BD,IND,06/05/2017,09:00:00,REGULAR,916848676,2087386866
69801,N208,R443,01-05-01,170 ST,BD,IND,06/05/2017,05:00:00,REGULAR,916848676,2087386866
69800,N208,R443,01-05-01,170 ST,BD,IND,06/05/2017,01:00:00,REGULAR,916848676,2087386866
69799,N208,R443,01-05-01,170 ST,BD,IND,06/04/2017,21:00:00,REGULAR,916848676,2087386866
69788,N208,R443,01-05-01,170 ST,BD,IND,06/03/2017,01:00:00,REGULAR,916848676,2087386866
69808,N208,R443,01-05-01,170 ST,BD,IND,06/06/2017,09:00:00,REGULAR,916848676,2087386866
69789,N208,R443,01-05-01,170 ST,BD,IND,06/03/2017,05:00:00,REGULAR,916848676,2087386866
69790,N208,R443,01-05-01,170 ST,BD,IND,06/03/2017,09:00:00,REGULAR,916848676,2087386866
69791,N208,R443,01-05-01,170 ST,BD,IND,06/03/2017,13:00:00,REGULAR,916848676,2087386866
69792,N208,R443,01-05-01,170 ST,BD,IND,06/03/2017,17:00:00,REGULAR,916848676,2087386866
69793,N208,R443,01-05-01,170 ST,BD,IND,06/03/2017,21:00:00,REGULAR,916848676,2087386866
69794,N208,R443,01-05-01,170 ST,BD,IND,06/04/2017,01:00:00,REGULAR,916848676,2087386866
69795,N208,R443,01-05-01,170 ST,BD,IND,06/04/2017,05:00:00,REGULAR,916848676,2087386866
69796,N208,R443,01-05-01,170 ST,BD,IND,06/04/2017,09:00:00,REGULAR,916848676,2087386866
69807,N208,R443,01-05-01,170 ST,BD,IND,06/06/2017,05:00:00,REGULAR,916848676,2087386866
69829,N208,R443,01-05-01,170 ST,BD,IND,06/09/2017,21:00:00,REGULAR,916848676,2087386866
69809,N208,R443,01-05-01,170 ST,BD,IND,06/06/2017,13:00:00,REGULAR,916848676,2087386866
69810,N208,R443,01-05-01,170 ST,BD,IND,06/06/2017,17:00:00,REGULAR,916848676,2087386866
69827,N208,R443,01-05-01,170 ST,BD,IND,06/09/2017,13:00:00,REGULAR,916848676,2087386866
69826,N208,R443,01-05-01,170 ST,BD,IND,06/09/2017,09:00:00,REGULAR,916848676,2087386866
69825,N208,R443,01-05-01,170 ST,BD,IND,06/09/2017,05:00:00,REGULAR,916848676,2087386866
69824,N208,R443,01-05-01,170 ST,BD,IND,06/09/2017,01:00:00,REGULAR,916848676,2087386866
69823,N208,R443,01-05-01,170 ST,BD,IND,06/08/2017,21:00:00,REGULAR,916848676,2087386866
69822,N208,R443,01-05-01,170 ST,BD,IND,06/08/2017,17:00:00,REGULAR,916848676,2087386866
...,...,...,...,...,...,...,...,...,...,...,...
19986,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/08/2017,16:00:00,REGULAR,6834,0
19985,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/08/2017,12:00:00,REGULAR,6834,0
19984,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/08/2017,08:00:00,REGULAR,6834,0
19982,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/08/2017,00:00:00,REGULAR,6833,0
19991,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/09/2017,12:00:00,REGULAR,6835,0
19981,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/07/2017,20:00:00,REGULAR,6832,0
19980,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/07/2017,16:00:00,REGULAR,6831,0
19979,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/07/2017,12:00:00,REGULAR,6831,0
19978,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/07/2017,08:00:00,REGULAR,6831,0
19977,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/07/2017,04:00:00,REGULAR,6831,0
19976,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/07/2017,00:00:00,REGULAR,6831,0
19990,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/09/2017,08:00:00,REGULAR,6835,0
19992,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/09/2017,16:00:00,REGULAR,6837,0
173154,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/05/2017,09:00:00,REGULAR,962,0
173147,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/04/2017,05:00:00,REGULAR,962,0
173153,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/05/2017,05:00:00,REGULAR,962,0
173152,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/05/2017,01:00:00,REGULAR,962,0
173151,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/04/2017,21:00:00,REGULAR,962,0
173150,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/04/2017,17:00:00,REGULAR,962,0
173149,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/04/2017,13:00:00,REGULAR,962,0
173148,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/04/2017,09:00:00,REGULAR,962,0
173146,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/04/2017,01:00:00,REGULAR,962,0
19993,C008,R099,00-04-00,DEKALB AV,BDNQR,BMT,06/09/2017,20:00:00,REGULAR,6838,0
173145,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/03/2017,21:00:00,REGULAR,962,0
173144,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/03/2017,17:00:00,REGULAR,962,0
173143,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/03/2017,13:00:00,REGULAR,962,0
173142,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/03/2017,09:00:00,REGULAR,962,0
173141,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/03/2017,05:00:00,REGULAR,962,0
173140,R417,R222,00-05-00,PARKCHESTER,6,IRT,06/03/2017,01:00:00,REGULAR,962,0
84556,N338,R128,01-05-00,SUTPHIN BLVD,F,IND,06/03/2017,17:00:00,REGULAR,1320,0